(use-modules (jtd))
(define *a* (make-parameter 0))
(define (demo02 . args)
    (let* ((b (+ (*a*) 1))
           (c (+ (*a*) b 2)))
      (if (< c 4)
          (jump-to-debugger))
      (simple-format #t "foo a= ~S\n" (*a*))
      (simple-format #t "foo b= ~S\n" b)
      (set! b 9)
      (simple-format #t "foo b= ~S\n" b)
      (simple-format #t "foo c= ~S\n" c)))
